---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meh-db-credentials
  namespace: meh
spec:
  encryptedData:
    password: AgCBx3+4EiJ0WydC4KkKJpH9aw7d1awjmjYOnxx8uPyEyrkdQzroC12Ql4i5oU2Dm1U8eKpMCLrtNQcKqe5aM4ftSDKc0EHs0PR4yPUjwbxqPWVDBqt6Su305gxbWNfmXPwAgAtJMEr47Dbmj3htGs7e61uhunF6oAqHslXG38lBP4Qr8f1DnzdV82Xr8kzwfOc5rq2hHtdyFJBljmRu+IKfrG8AkfR6lwGm4sl4ba7iHg3KJlBDMz08MlIiS0eFOCKm+oH3nrheKh866A0UornnCxXjWWnVgRb4uR7trJEOGSJ8z/+Ne424G3xRbcDS9PvZNPWdIchSF6vp0H83qX0nkYW6ZBwmp1E3IIJnFc1WwzEeL6LcCr17Sqdpu6OXhznKca6UZ1aW23N81pzt8+EeScQaTDUaBKCQnllZRNbulnUJysf+1BQKNofjdpqK/mjYU79JdzzI6l66o5y0/yLL9SVZAow4xHBNtuhPLReM70VOc6oCbVoGToBYKjxp74438gC61RM3P1nocuAXqSZyLTGXAXLKRBhXZ3zV6JgYqd2PtXPmb51REbsE3Weir1PYzDRhHx9YVdzbRi+O3DSgK3lbQax0VvcmuoAVg+Xzq+PgPmoXEvuBCR/G+t7+PJwGjzILnV7Vkjw79A6s4wv98kZMnRJjo+KSnzBPQWm+TZO85SKIYbBz0xrEq1LqOcLPTbFE7X+Qptbgg4kW4RcYHtSgSg==
    username: AgBstFM3eeQ34fR9wnbwV0JGJ1qP/ALW6hG5TFC8+TM3GVEcbvbPzT8e2PypCuhJXr3rgfjMSOmA//Fnzyu6QcqeagzJCqOsp2vnbK+J5LlGHc3mWDzrK2W0QVUyn+SUFjBKlXZkm2BqDLc/tT0HbZ6cpouXi8U8VMOBthBeVPLfFvL7Sb2jWf5p7v52E9Y3PFBjNtEBOWhML7zl31R/fOodmSmWPZdZ/rTxJgeuTP0Jf94X/kegediMQZaI9jHtZGvSZEx0YeJ0KzVZ1Q3XlIvz6vhfYCCEpPhvMBkofUOTZlaI9iuQHxyaf2tJCA+b1qaB/tE+SGbUIfk0BXfjQlnGXUoI5K+Gammq+fGFL3NsZg/bS0AFXGgpWQ+S/tFHCFFWDvHZ/ZA7NixPt1Ci/CPcOnCW2P0aa3N8qNv+zODT6g3B3ikqlBIvd/Bib81O09Rx4RjmNdE76V3K2p1oSljELrbdgrvkEx+A5+0Zg5W45YejpgK2p8Yb1ldMmYPr+Xj6FsVZyZdqKyHqRtfUMT2NCCPxf0fBEuL+gVhBprbre622q9hkRGTgV74nfawBUZ9norgGxpHnOGvXrgmMHOAV48SxW5i8xELJNfnqJ3kmmOjIFferzK86KdXD9xDpAkL/vDoKkkXu3Md/fJS8AT79ksN0WutueJ0A+8dpGZDUYeGiCu1BHS0sEQpNEOmGX7w1QUM=
  template:
    metadata:
      creationTimestamp: null
      name: meh-db-credentials
      namespace: meh
    type: Opaque
