---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meh-auth
  namespace: meh
spec:
  encryptedData:
    secret: AgBr2L3G/Jmsx3IXky7ikwsk/GAkBQvqwXYSNNWDf3USML8QjxHD+OWTAsil5lblq5DtYkz7ftHXXnxkc8Kv7zd/b8/ioz4paxqgie1KuU3OU8dGQNN1gLylw+SMm2jd/wvzfWr/kO8XvdV1yfj5jF8zvdK96s5xTJ0VD2teBFy/c+vYeOcsR1v0bqyH0mFdttAKQHyTYXxguGqRlk6lW07XdFQ/vylfX9jbbL/gSVynDaE29pqEZYi1h/tySejfUEKkaNWIa3MPCrVVF2q9SOXk1tMawbN8fgoy76JXVT06cVLyzVhFJQcUB60Hd8rzdGWineFqs/6diBU6X8vlW3lANZEk3fb+Y+4rUM7FwAthcyDAoZ2MB2bKezgGfaxTLbi03o411FWnPaPYyhRExI8FS0v7GecQ/Hb8PNxSlfNc0KOq5oSnG03vcFPrYVVb+fTBL7s3/XdZ8OngdY8bdmQMk1j9E91LO9znu3d4xVr3SnpZBszWvniEb0EuZ97gC7T51YiYkcGcM3CdL4yJTKurcxe1rCmnHdAgX26R/z9ufliMpJfEy5U6cZtZPjZWwwBEyBWPkAmi5m33xAIGQ57pe0P90DfYiB0EKoylowtNEdbr+MNsdzMz7+j5LCcFSn/QpZ6jl9RRHotY2xCZZqxXXz6HI9HX/cmQ9/S+VLpMcQN0gdPpbVJ3QEyuPHToAM32PUn6WGvMXrxpw93ObB+8oUG4UqLehX2PL89LjYDMoQ==
  template:
    metadata:
      creationTimestamp: null
      name: meh-auth
      namespace: meh
    type: Opaque
