---
replicaCount: 2

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "dns01-cloudflare-cluster-issuer-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "meh.nailforge.dev"
      paths:
        - path: "/"
          pathType: "Prefix"
          servicePortName: "http"
  tls:
    - hosts:
        - "meh.nailforge.dev"
      secretName: "meh-tls"

app:
  env:
    - name: "PORT"
      value: "8080"
    - name: "PROMETHEUS_PORT"
      value: "3000"
    - name: "LOG_LEVEL"
      value: "INFO"
    - name: "DATABASE_HOST"
      value: "meh-postgresql-rw"
    - name: "DATABASE_PORT"
      value: "5432"
    - name: "DATABASE_USER"
      valueFrom:
        secretKeyRef:
          name: "meh-db-credentials"
          key: "username"
    - name: "DATABASE_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: "meh-db-credentials"
          key: "password"
    - name: "SECRET"
      valueFrom:
        secretKeyRef:
          name: "meh-auth"
          key: "secret"

...
